# Generated by Django 2.2.5 on 2019-09-10 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='slug',
            field=models.SlugField(default=None, max_length=60, unique=True),
        ),
    ]
