# Generated by Django 2.2.5 on 2019-09-10 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctors', '0002_doctor_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='slug',
        ),
    ]
